#include "UserManager.h"
#include <iostream>
#include <string>
#include <limits>

void clearScreen() {
    #ifdef _WIN32
        system("cls");
    #else
        system("clear");
    #endif
}

void showMenu() {
    clearScreen();
    std::cout << "\n=== HE THONG QUAN LY VI DIEM THUONG ===\n";
    std::cout << "1. Dang ky tai khoan\n";
    std::cout << "2. Dang nhap\n";
    std::cout << "3. Thoat\n";
    std::cout << "Chon chuc nang (1-3): ";
}

void registerUser(UserManager& userManager) {
    clearScreen();
    std::string username, password, fullName, email, phoneNumber;
    bool isPasswordAutoGenerated = false;
    
    std::cout << "\n=== DANG KY TAI KHOAN ===\n";
    
    std::cout << "Nhap ten dang nhap: ";
    std::cin >> username;
    
    std::cout << "Nhap mat khau (neu ban de trong thi he thong se tu sinh mat khau): ";
    std::cin.ignore(std::numeric_limits<std::streamsize>::max(), '\n');
    std::getline(std::cin, password);
    
    if (password.empty()) {
        password = userManager.generateRandomPassword();
        isPasswordAutoGenerated = true;
        std::cout << "\nMat khau tu sinh: " << password << "\n";
        std::cout << "Vui long luu lai mat khau nay va doi mat khau trong lan dang nhap dau tien.\n";
    }
    
    std::cout << "Nhap ho va ten: ";
    std::getline(std::cin, fullName);
    
    std::cout << "Nhap email (email phai co dang example@domain.com): ";
    std::cin >> email;
    
    std::cout << "Nhap so dien thoai (so dien thoai phai co 10 chu so): ";
    std::cin >> phoneNumber;
    
    auto result = userManager.registerUser(username, password, fullName, email, phoneNumber, isPasswordAutoGenerated);
    switch (result) {
        case RegisterResult::SUCCESS:
            std::cout << "Dang ky thanh cong!\n";
            break;
        case RegisterResult::USERNAME_EXISTS:
            std::cout << "Dang ky that bai! Ten dang nhap da ton tai.\n";
            break;
        case RegisterResult::INVALID_USERNAME:
            std::cout << "Dang ky that bai! Ten dang nhap khong hop le.\n";
            break;
        case RegisterResult::INVALID_PASSWORD:
            std::cout << "Dang ky that bai! Mat khau khong hop le.\n";
            break;
        case RegisterResult::INVALID_EMAIL:
            std::cout << "Dang ky that bai! Email khong hop le.\n";
            break;
        case RegisterResult::INVALID_PHONE:
            std::cout << "Dang ky that bai! So dien thoai khong hop le.\n";
            break;
        case RegisterResult::FILE_ERROR:
            std::cout << "Dang ky that bai! Khong the luu thong tin.\n";
            break;
    }
}

void login(UserManager& userManager) {
    clearScreen();
    std::string username, password;
    
    std::cout << "\n=== DANG NHAP ===\n";
    
    std::cout << "Nhap ten dang nhap: ";
    std::cin >> username;
    
    std::cout << "Nhap mat khau: ";
    std::cin >> password;
    
    if (userManager.login(username, password)) {
        std::cout << "Dang nhap thanh cong!\n";
        
        // Kiểm tra và yêu cầu đổi mật khẩu nếu là mật khẩu tự sinh
        if (userManager.isPasswordAutoGenerated(username)) {
            std::cout << "\nDay la lan dau dang nhap voi mat khau tu sinh.\n";
            std::cout << "Vui long doi mat khau cua ban.\n";
            
            std::string newPassword;
            std::cout << "Nhap mat khau moi: ";
            std::cin >> newPassword;
            
            if (userManager.changePassword(username, password, newPassword)) {
                std::cout << "Doi mat khau thanh cong!\n";
            } else {
                std::cout << "Doi mat khau that bai! Vui long thu lai sau.\n";
            }
        }
        
        // TODO: Add user menu here
    } else {
        std::cout << "Dang nhap that bai! Vui long kiem tra lai thong tin.\n";
    }
}

int main() {
    UserManager userManager("../data/users.txt");
    int choice;
    
    while (true) {
        showMenu();
        std::cin >> choice;
        
        switch (choice) {
            case 1:
                registerUser(userManager);
                break;
            case 2:
                login(userManager);
                break;
            case 3:
                clearScreen();
                std::cout << "Cam on ban da su dung chuong trinh!\n";
                return 0;
            default:
                std::cout << "Lua chon khong hop le! Vui long chon lai.\n";
        }
        
        std::cout << "\nNhan Enter de tiep tuc...";
        std::cin.ignore(std::numeric_limits<std::streamsize>::max(), '\n');
        std::cin.get();
    }
    
    return 0;
} 