#pragma once
#include <string>
#include <vector>
#include <map>
#include <fstream>
#include <sstream>
#include <iomanip>
#include <regex>
#include "User.h"
#include "OTPManager.h"

enum class RegisterResult {
    SUCCESS,
    USERNAME_EXISTS,
    INVALID_USERNAME,
    INVALID_PASSWORD,
    INVALID_EMAIL,
    INVALID_PHONE,
    FILE_ERROR
};

class UserManager {
private:
    std::map<std::string, User> users;
    std::string dataFile;
    OTPManager otpManager;

    bool isUsernameExists(const std::string& username);
    void sendLoginInfoToUser(const std::string& email, const std::string& username, 
                            const std::string& password);
    bool saveUsers();
    void loadUsers();
    bool isValidEmail(const std::string& email);
    bool isValidPhoneNumber(const std::string& phoneNumber);

public:
    UserManager(const std::string& usersPath);
    
    RegisterResult registerUser(const std::string& username, const std::string& password, 
                              const std::string& fullName, const std::string& email, 
                              const std::string& phoneNumber, bool isPasswordAutoGenerated = false);
                     
    bool login(const std::string& username, const std::string& password);
    std::string generateRandomPassword();
    bool isPasswordAutoGenerated(const std::string& username);
    bool changePassword(const std::string& username, const std::string& oldPassword, 
                       const std::string& newPassword);

    // OTP functions
    std::string setupOTP(const std::string& username);
    bool verifyOTP(const std::string& username, const std::string& otp);
}; 